// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/hokkung/go-tumboon/config"
	"github.com/hokkung/go-tumboon/internal/runner"
	service2 "github.com/hokkung/go-tumboon/internal/service/donation"
	"github.com/hokkung/go-tumboon/internal/service/payment"
	"github.com/hokkung/go-tumboon/internal/validator"
	"github.com/hokkung/go-tumboon/pkg/omise"
)

// Injectors from wire.go:

func InitializeMakePermitRunnerApplication() (*MakePermitApplication, func(), error) {
	configuration, err := config.ProvideConfiguration()
	if err != nil {
		return nil, nil, err
	}
	omiseClient, err := omisecli.ProvideOmiseClient(configuration)
	if err != nil {
		return nil, nil, err
	}
	paymentService := service.ProvideOmisePaymentService(omiseClient)
	validate := validator.NewCustomValidator()
	donationService := service2.ProvideDonationService(paymentService, configuration, validate)
	donationRunner := runner.NewDonationRunner(donationService)
	makePermitApplication := &MakePermitApplication{
		Runner: donationRunner,
	}
	return makePermitApplication, func() {
	}, nil
}
