// Code generated by MockGen. DO NOT EDIT.
// Source: omise.go

// Package mock_omisecli is a generated GoMock package.
package mock_omisecli

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOmiseClient is a mock of OmiseClient interface.
type MockOmiseClient struct {
	ctrl     *gomock.Controller
	recorder *MockOmiseClientMockRecorder
}

// MockOmiseClientMockRecorder is the mock recorder for MockOmiseClient.
type MockOmiseClientMockRecorder struct {
	mock *MockOmiseClient
}

// NewMockOmiseClient creates a new mock instance.
func NewMockOmiseClient(ctrl *gomock.Controller) *MockOmiseClient {
	mock := &MockOmiseClient{ctrl: ctrl}
	mock.recorder = &MockOmiseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOmiseClient) EXPECT() *MockOmiseClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockOmiseClient) Do(result, op interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", result, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockOmiseClientMockRecorder) Do(result, op interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockOmiseClient)(nil).Do), result, op)
}
